import type { Metadata } from "next";
import Navbar from "@/Components/Navbar/Navbar";
import AppProvider from "@/ContextAPI/AppContext";

import "./scss/styles.scss";
import Drawer from "@/Components/Aside/Drawer/Drawer";

export const metadata: Metadata = {
  title: "Video Platfor | MyTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Navbar />
          <Drawer />
        </AppProvider>

        {children}
      </body>
    </html>
  );
}
